language: ruby
rvm:
- 2.1.2
deploy:
  provider: codedeploy
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
  key: latest/MyApp.zip
  application: MyApp
  deployment_group: MyDeploymentGroup
