deploy:
- provider: s3
  access_key_id: AKIAJIACEZZVRIM5J63Q
  secret_access_key: &70203069521860
    secure: oufXpdcFhpGnfOA9SqF+da25vFc6nkGkKsCTz6qnrMbzR5nJ4S6mFdHf2iGORnp/c44BIelSrisDriFwbwJCH3QADYQ6ziZ5cztrwnxpO9YHGiHN4RjYPzO3TQI72UFh51Qw95dZWK88yvmLNOA9MIW8Z/DJAfVWCy/5tbEgW3TGhes96MSyjnNESBuFuCtVPQ1kTDhOpJOQ2C73rPNIn95JtfisX4MNTBCC5tuc3WL6z4AMmpT8WnZAzSY6wIA8c8m+WjRNaYIWwHlAz5fxRxRzYIeLPL4C3O9o2F77Gw4ep6yieBSexQF2v6KPcq3ohYZ+ERSov1vvpCkjKzBPN1TBzV9UWobejok/QVCcl/2eCqBEmbFk1fqGYwVlWPXQW3Pcadv5UvBptxVf/tb9TShmwInjUbSftrELJ9mesxuRSt4FM6Yt4tWH3+3jN9AR4FGaBfwR2qYxm6oruvVfTLeFTio9TaEP47vufZ2Qxye6/sSFLvHONWmJTPmmTWKM2VT/1Hwt/s+9IAzZs7tDNA9e7slh04tTWeLsIRRN3x7CwVuAUUKTWge/R8qapYCqeFZobU67hlUyC4MJU5+SaopRqKwSPFIA3Mq5qX+ltlZegHOL/9vBQFhX26y0lvOQmFf9sEl7Y9fFOQ88oVJ6tls/D+JpX6PTL5T11fTzTUQ=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &70203057526140
    repo: jagatveer/CodeDeployGitHubDemo
  bucket: ops-587
  upload_dir: sample
- provider: codedeploy
  access_key_id: AKIAJIACEZZVRIM5J63Q
  secret_access_key: *70203069521860
  bucket: ops-587
  key: sample/githubtest.tar.gz
  bundle_type: tgz
  application: OPS-587
  deployment_group: OPS-587
  on: *70203057526140
before_deploy:
- mkdir -p dpl_cd_upload
- mv githubtest.tar.gz dpl_cd_upload/githubtest.tar.gz
