deploy:
- provider: s3
  access_key_id: AKIAJ2W67PFHEGNE4U4A
  secret_access_key: &70114028490460
    secure: HZ7lwR9Y11iVJ+Ggn5C5GTp1KTepzGns5n8cCCbQnqjBb3dq/wkkJd/D6rTQDXxYr1KU7CFFk3SuWNmmG+x3RWvNza4TW/5Hw33PSykPM/F60/YFv48D8fhP6c7+z6HBuTPn7rmckSiiod1AMfNJqN+EV0OHFxKFS0Atp8zvPvneKV4jwJt3EazBfb1ZC9Wrl/ypOaB0JhkPaUVd/iI+uwy+K6tdce6o5iJI+gMcbHZ62hH1xHdt6ZczRlygxeln7l2ygaHxleL6XVXeUJkVbADf8/0VUkLAYxpwFCvZM+bf65iLgyRn64REA0672KwYBqit6XwuvPF5Tc59A33CAT+68U82bE8ilO4zaOeP1PW8jokGM5A3RZk8AFJZ3316DAwaP5Y+duqXHI8EW3RlCq6r5GDW1ZOxJF+mwbC2jMuLlr4NL7RhxIopbK5aTpcMuyumqJkazo4bGqxmhAJqVvzhNJ0bVTejRtDZxYwGBNLhPWHY+E4EvTjCEZ5VrLOtk967B74Yt92Mc+Nu/4n7NmCJWraHLPlC4o9TMvV9V10O7Dwxb4C9vUEfIETsCJ01kuyi/xzFHtFtbUHcYJ7PPYI0C1wySQPYce1+c/rFUcwLrSxlD6LFzIdzsNTnQU/nFzUSZ5k/8YlfN1OCD0H6Ok7MfjPsMJneQqjYy4Wv5Ck=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &70114028497260
    repo: jagatveer/CodeDeployGitHubDemo
  bucket: ops-587
  upload_dir: sample
- provider: codedeploy
  access_key_id: AKIAJ2W67PFHEGNE4U4A
  secret_access_key: *70114028490460
  bucket: ops-587
  key: sample/CodeDeployGitHubDemo-Ops-587.zip
  bundle_type: zip
  application: CodeDeployGitHubDemo-Ops-587
  deployment_group: CodeDeployGitHubDemo-Ops-587
  on: *70114028497260
before_deploy:
- mkdir -p dpl_cd_upload
- mv index.html dpl_cd_upload/CodeDeployGitHubDemo-Ops-587.zip
