development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 10
  username: <%= ENV['USER_TEST'] %>
  template: template1
  password: <%= ENV['PASSKEY_TEST'] %>
  port: 5432
  sslmode: disable
test:
